#!/usr/bin/env python3
"""
Minseong Evidence Radar v0.3
Clinical evidence filter + expanded KCD mapping + condition-grouped briefs.

Input: v2 JSON generated by fetch_evidence_v2.py
Output:
  evidence-*-clinical.json
  evidence-*-clinical.md
  evidence-briefs/*.md

No web/API write and no automatic wiki publishing.
"""
import argparse, json, re
from pathlib import Path
from collections import defaultdict

NONCLINICAL_TERMS=[
 "student satisfaction","education","curriculum","medical education",
 "continuing professional development","search trends","data lab",
 "utilization","health panel","economic evaluation","cost-utility",
 "cost-effectiveness","markov analysis","expert opinions",
 "current usage","needs analysis","survey on the current usage"
]
CLINICAL_TYPES={"Systematic review & meta-analysis","Scoping review","RCT","RCT protocol",
                "Case report","Cross-sectional study","Pilot study","Other human study"}

KCD_RULES=[
(["lumbar spinal stenosis","요추 척추관 협착","요추관 협착"],"M48.06","요추 척추관협착증","conditions/lumbar-spinal-stenosis/","척추·요통"),
(["cervical disc herniation","경추 추간판 탈출"],"M50.1","경추 추간판탈출증","conditions/cervical-disc-herniation/","경추·목통증"),
(["rotator cuff","회전근개"],"M75.1","회전근개 질환","conditions/rotator-cuff-disease/","어깨"),
(["temporomandibular","턱관절"],"K07.6","턱관절장애","conditions/temporomandibular-disorder/","턱관절"),
(["tension headache","긴장성 두통"],"G44.2","긴장형두통","conditions/tension-type-headache/","두통"),
(["myofascial pain","근막통증"],"M79.1","근막통증증후군","conditions/myofascial-pain-syndrome/","근막·통증"),
(["peripheral neuropathy","말초신경병증"],"G62.9","말초신경병증","conditions/peripheral-neuropathy/","말초신경"),
(["diabetic polyneuropathy","당뇨병성 다발신경병증"],"G63.2","당뇨병성 다발신경병증","conditions/diabetic-polyneuropathy/","말초신경"),
(["cervical spondylotic myelopathy","경추 척수증"],"M47.12","경추 척수증","conditions/cervical-spondylotic-myelopathy/","경추·목통증"),
(["chronic knee pain","무릎 통증"],"M25.56","무릎통증","conditions/knee-pain/","무릎"),
(["complex regional pain syndrome","복합부위통증증후군"],"G90.5","복합부위통증증후군","conditions/complex-regional-pain-syndrome/","말초신경"),
(["hypothyroidism","갑상선 기능 저하"],"E03.9","갑상선기능저하증","conditions/hypothyroidism/","내과"),
(["conductive hearing loss","전음성 난청"],"H90.2","전음성 난청","conditions/conductive-hearing-loss/","이비인후"),
(["verruca vulgaris","심상유","사마귀"],"B07","사마귀","conditions/warts/","피부"),
(["dyshidrotic eczema","한포진"],"L30.1","한포진","conditions/dyshidrotic-eczema/","피부"),
(["folliculitis","모낭염"],"L73.9","모낭염","conditions/folliculitis/","피부"),
(["mild cognitive impairment","경도인지장애"],"R41.8","경도인지장애","conditions/mild-cognitive-impairment/","신경·인지"),
(["meniscus tear","반월상 연골"],"S83.2","반월상연골 손상","conditions/meniscus-tear/","무릎"),
]

def text_of(r):
    return " ".join([str(r.get("title","")),str(r.get("keywords","")),
                     str(r.get("pico","")),str(r.get("clinical_summary",""))]).lower()

def add_kcd(r):
    text=text_of(r)
    existing={(x.get("code"),x.get("label")) for x in r.get("kcd_candidates",[])}
    for terms,code,label,path,group in KCD_RULES:
        if any(t.lower() in text for t in terms) and (code,label) not in existing:
            r.setdefault("kcd_candidates",[]).append(
              {"code":code,"label":label,"status":"candidate","archive_path":path,"group":group})
            r.setdefault("archive_links",[]).append("/"+path)
    r["archive_links"]=list(dict.fromkeys(r.get("archive_links",[])))
    return r

def clinical_relevance(r):
    text=text_of(r)
    reasons=[x for x in NONCLINICAL_TERMS if x in text]
    # Actual clinical efficacy/safety RCTs remain even if title contains economic wording
    strong=r.get("study_type") in {"Systematic review & meta-analysis","Scoping review","RCT",
                                   "RCT protocol","Case report","Pilot study"}
    if reasons and not strong:
        return False,reasons
    # remove education/policy even if mislabeled
    if any(x in text for x in ["student satisfaction","curriculum improvement","medical education"]):
        return False,["education"]
    return True,[]

def group_for(r):
    labels=" ".join(x.get("label","") for x in r.get("kcd_candidates",[]))
    text=(labels+" "+text_of(r)).lower()
    groups=[
      ("척추·요통",["요통","요추","lumbar","dorsopath"]),
      ("경추·목통증",["경추","목 통증","cervical","neck pain"]),
      ("어깨",["오십견","유착성","회전근개","shoulder","rotator cuff"]),
      ("팔꿈치",["외측상과","epicondyl"]),
      ("무릎",["무릎","knee","meniscus"]),
      ("말초신경",["신경","neuropathy","nerve entrapment","crps"]),
      ("두통",["두통","headache"]),
      ("턱관절",["턱관절","temporomandibular"]),
      ("피부",["피부","eczema","alopecia","wart","follicul"]),
      ("초음파 유도 약침",["ultrasound-guided","초음파 유도"]),
    ]
    out=[g for g,terms in groups if any(t in text for t in terms)]
    return out or ["기타 임상"]

def evidence_level(study_type):
    return {
      "Systematic review & meta-analysis":"A",
      "Scoping review":"B",
      "RCT":"B",
      "Pilot study":"C",
      "Cross-sectional study":"C",
      "Other human study":"C",
      "Case report":"D",
      "RCT protocol":"P"
    }.get(study_type,"C")

def brief(group,records):
    records=sorted(records,key=lambda r:(r.get("priority_score",0),str(r.get("published_date",""))),reverse=True)
    out=[f"# Evidence Brief — {group}","",
         f"- 임상 후보: {len(records)}건",
         "- 자동 생성 검토용. 게시 전 원문·KCD·PICO·링크를 확인합니다.","",
         "|근거층|연도|연구|질환/KCD|치료|PMID/DOI|",
         "|---|---|---|---|---|---|"]
    for r in records:
        k=", ".join(x.get("code","")+" "+x.get("label","") for x in r.get("kcd_candidates",[])) or "-"
        src=r.get("pmid") or r.get("doi") or "-"
        title=str(r.get("title","")).replace("|","/")
        out.append(f"|{evidence_level(r.get('study_type'))} {r.get('study_type')}|{r.get('published_date','-')}|{title}|{k}|{', '.join(r.get('treatment_tags',[]))}|{src}|")
    out += ["","## 우선 검토 연구",""]
    for r in records[:10]:
        out += [f"### {r.get('title')}","",
                f"- 연구유형: {r.get('study_type')} / 우선순위 {r.get('priority_score')}",
                f"- KCD 후보: {', '.join(x.get('code','')+' '+x.get('label','') for x in r.get('kcd_candidates',[])) or '-'}",
                f"- P: {r.get('pico',{}).get('population') or '-'}",
                f"- I: {r.get('pico',{}).get('intervention') or '-'}",
                f"- C: {r.get('pico',{}).get('comparator') or '-'}",
                f"- O: {r.get('pico',{}).get('outcomes') or '-'}",
                f"- 연결 후보: {', '.join(r.get('archive_links',[])) or '-'}",""]
    return "\n".join(out)

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("input",help="v2 JSON file")
    ap.add_argument("--prefix",default="evidence-pharmacopuncture")
    args=ap.parse_args()
    rows=json.loads(Path(args.input).read_text(encoding="utf-8"))
    kept=[]; excluded=[]
    for r in rows:
        r=add_kcd(r)
        ok,reasons=clinical_relevance(r)
        r["clinical_evidence"]=ok
        r["exclusion_reasons"]=reasons
        r["evidence_level"]=evidence_level(r.get("study_type"))
        r["condition_groups"]=group_for(r)
        (kept if ok else excluded).append(r)

    out=Path(f"{args.prefix}-clinical.json")
    out.write_text(json.dumps(kept,ensure_ascii=False,indent=2),encoding="utf-8")

    groups=defaultdict(list)
    for r in kept:
        for g in r["condition_groups"]: groups[g].append(r)

    bdir=Path("evidence-briefs"); bdir.mkdir(exist_ok=True)
    safe_names={"척추·요통":"spine-low-back","경추·목통증":"cervical-neck","어깨":"shoulder",
                "팔꿈치":"elbow","무릎":"knee","말초신경":"peripheral-nerve","두통":"headache",
                "턱관절":"tmj","피부":"dermatology","초음파 유도 약침":"ultrasound-guided",
                "기타 임상":"other-clinical"}
    for g,recs in groups.items():
        (bdir/(safe_names.get(g,"other")+".md")).write_text(brief(g,recs),encoding="utf-8")

    summary=[f"# Clinical Evidence Radar — {args.prefix}","",
             f"- v2 입력: {len(rows)}건",
             f"- 임상 Evidence 통과: {len(kept)}건",
             f"- 교육·정책·이용 등 제외: {len(excluded)}건","",
             "## 질환군",""]
    for g,recs in sorted(groups.items(),key=lambda x:len(x[1]),reverse=True):
        summary.append(f"- {g}: {len(recs)}건 → `evidence-briefs/{safe_names.get(g,'other')}.md`")
    summary += ["","## 제외 목록",""]
    for r in excluded:
        summary.append(f"- {r.get('title')} — {', '.join(r.get('exclusion_reasons',[]))}")
    Path(f"{args.prefix}-clinical.md").write_text("\n".join(summary),encoding="utf-8")
    print(f"input {len(rows)} -> clinical {len(kept)} -> excluded {len(excluded)} -> {len(groups)} briefs")

if __name__=="__main__":
    main()
