$ErrorActionPreference='Stop'
function U($f,$s,$e,$b){$t=Get-Content $f -Raw -Encoding UTF8;if($t.Contains($s)){$p=[regex]::Escape($s)+'.*?'+[regex]::Escape($e);$t=[regex]::Replace($t,$p,$b,[Text.RegularExpressions.RegexOptions]::Singleline)}else{$t=$t.TrimEnd()+"`r`n`r`n"+$b};Set-Content $f $t -Encoding UTF8}
function F($names,$pat){foreach($n in $names){if(Test-Path $n){return $n}};$h=Get-ChildItem docs -Recurse -Filter *.md -File|?{(Get-Content $_.FullName -Raw -Encoding UTF8)-match $pat}|Select-Object -First 1;if($h){return $h.FullName}}
try{
$R=Split-Path -Parent $MyInvocation.MyCommand.Path;Set-Location $R;if(!(Test-Path docs)){throw 'docs folder not found'}
$bk='_backup_meridian19_'+(Get-Date -Format 'yyyyMMdd-HHmmss');New-Item -ItemType Directory -Force $bk|Out-Null
New-Item -ItemType Directory -Force 'docs\acupuncture\meridians'|Out-Null;New-Item -ItemType Directory -Force 'docs\acupuncture\extraordinary'|Out-Null
$M=@(
@('lu','수태음폐경 LU','폐·호흡기·인후와 상지 전내측','LU1 중부 · LU5 척택 · LU7 열결 · LU9 태연'),@('li','수양명대장경 LI','상지 외측과 두면부','LI4 합곡 · LI10 수삼리 · LI11 곡지 · LI15 견우 · LI20 영향'),@('st','족양명위경 ST','두면·흉복부·하지 전외측과 비위','ST25 천추 · ST36 족삼리 · ST40 풍륭 · ST44 내정'),@('sp','족태음비경 SP','하지 내측·복부와 비위·수습·혈','SP4 공손 · SP6 삼음교 · SP9 음릉천 · SP10 혈해'),@('ht','수소음심경 HT','심계·수면과 상지 내측','HT3 소해 · HT5 통리 · HT7 신문'),@('si','수태양소장경 SI','상지 후외측·견갑·경항','SI3 후계 · SI6 양로 · SI11 천종'),@('bl','족태양방광경 BL','두항·등·요부·하지 후면과 배수혈','BL10 천주 · BL13 폐수 · BL18 간수 · BL20 비수 · BL23 신수 · BL25 대장수 · BL40 위중 · BL57 승산 · BL60 곤륜'),@('ki','족소음신경 KI','족저·하지 내측·복흉부와 신허·배뇨','KI1 용천 · KI3 태계 · KI6 조해 · KI7 복류'),@('pc','수궐음심포경 PC','흉부·심계·오심·상지 전면','PC6 내관 · PC7 대릉'),@('te','수소양삼초경 TE','상지 외측·견부·측두부·이부','TE5 외관 · TE6 지구 · TE17 예풍'),@('gb','족소양담경 GB','측두·경견·체간 측면·하지 외측','GB20 풍지 · GB21 견정 · GB30 환도 · GB34 양릉천 · GB39 현종 · GB40 구허'),@('lr','족궐음간경 LR','족부·하지 내측·복부와 간울·기혈','LR3 태충 · LR8 곡천 · LR13 장문 · LR14 기문'))
foreach($m in $M){$p='docs\acupuncture\meridians\'+$m[0]+'.md';$x="---`r`ntitle: `"$($m[1])`"`r`ndescription: `"$($m[1])의 유주, 대표 경혈과 임상 연결을 정리합니다.`"`r`ntags: [십이경맥, 경락, 침구]`r`n---`r`n# $($m[1])`r`n`r`n## 경맥 개요`r`n$($m[2])를 연결합니다.`r`n`r`n## 대표 경혈`r`n$($m[3])`r`n`r`n## 임상적으로 읽는 방법`r`n유주·표리관계·특정혈·국소 해부학·변증과 배혈을 함께 살펴봅니다.`r`n`r`n→ [십이경맥 전체](index.md)`r`n→ [경혈 임상 지식망](../../acupoint-network/)";Set-Content $p $x -Encoding UTF8}
$idx="# 십이경맥 임상 지도`r`n`r`n1. [수태음폐경 LU](lu.md)`r`n2. [수양명대장경 LI](li.md)`r`n3. [족양명위경 ST](st.md)`r`n4. [족태음비경 SP](sp.md)`r`n5. [수소음심경 HT](ht.md)`r`n6. [수태양소장경 SI](si.md)`r`n7. [족태양방광경 BL](bl.md)`r`n8. [족소음신경 KI](ki.md)`r`n9. [수궐음심포경 PC](pc.md)`r`n10. [수소양삼초경 TE](te.md)`r`n11. [족소양담경 GB](gb.md)`r`n12. [족궐음간경 LR](lr.md)`r`n`r`n## 표리 관계`r`n폐↔대장 · 위↔비 · 심↔소장 · 방광↔신 · 심포↔삼초 · 담↔간`r`n`r`n→ [기경팔맥](../extraordinary/index.md)";Set-Content 'docs\acupuncture\meridians\index.md' $idx -Encoding UTF8
$E=@(@('ren','임맥(任脈) CV','전면 정중선·음경맥·하복부','CV4 관원 · CV6 기해 · CV12 중완 · CV17 전중'),@('du','독맥(督脈) GV','후면 정중선·척주·두항·양경맥','GV4 명문 · GV14 대추 · GV20 백회 · GV26 수구'),@('chong','충맥(衝脈)','기혈·충임·복부','공손 SP4 ↔ 내관 PC6'),@('dai','대맥(帶脈)','허리둘레·종적 경맥 연결','족임읍 GB41 ↔ 외관 TE5'),@('yinqiao','음교맥(陰蹻脈)','하지 내측·수면·안검','조해 KI6 ↔ 열결 LU7'),@('yangqiao','양교맥(陽蹻脈)','하지 외측·운동·각성','신맥 BL62 ↔ 후계 SI3'),@('yinwei','음유맥(陰維脈)','음경 연결·흉복부','내관 PC6 ↔ 공손 SP4'),@('yangwei','양유맥(陽維脈)','양경 연결·소양·표부','외관 TE5 ↔ 족임읍 GB41'))
foreach($e in $E){$p='docs\acupuncture\extraordinary\'+$e[0]+'.md';$x="# $($e[1])`r`n`r`n## 핵심`r`n$($e[2])와 관련된 기경입니다.`r`n`r`n## 대표 연결`r`n$($e[3])`r`n`r`n기경팔맥은 십이경맥과 고립시키지 않고 팔맥교회혈·임독맥·증상과 함께 봅니다.`r`n`r`n→ [기경팔맥 전체](index.md)";Set-Content $p $x -Encoding UTF8}
$ei="# 기경팔맥 임상 지도`r`n`r`n[임맥](ren.md) · [독맥](du.md) · [충맥](chong.md) · [대맥](dai.md) · [음교맥](yinqiao.md) · [양교맥](yangqiao.md) · [음유맥](yinwei.md) · [양유맥](yangwei.md)`r`n`r`n## 팔맥교회혈`r`n공손 SP4↔내관 PC6 · 족임읍 GB41↔외관 TE5 · 후계 SI3↔신맥 BL62 · 열결 LU7↔조해 KI6`r`n`r`n임맥과 독맥은 자체 경혈 체계를 갖는 기경팔맥의 핵심 두 맥입니다.`r`n`r`n→ [십이경맥](../meridians/index.md)";Set-Content 'docs\acupuncture\extraordinary\index.md' $ei -Encoding UTF8
$m=F @('docs\meridian-network\index.md','docs\meridian-network.md','docs\acupuncture\meridian-network.md') '경락.*지식망|meridian-network';if(!$m){throw 'meridian-network source not found'};Copy-Item $m (Join-Path $bk 'meridian-network.md') -Force
$mb="<!-- MERIDIAN_EXPANSION_19_START -->`r`n## 십이경맥·기경팔맥 확장`r`n- [십이경맥 전체 지도](../acupuncture/meridians/index.md)`r`n- [임맥](../acupuncture/extraordinary/ren.md) · [독맥](../acupuncture/extraordinary/du.md)`r`n- [기경팔맥 전체 지도](../acupuncture/extraordinary/index.md)`r`n`r`n### 팔맥교회혈`r`n공손↔내관 · 족임읍↔외관 · 후계↔신맥 · 열결↔조해`r`n<!-- MERIDIAN_EXPANSION_19_END -->";$dr=(Resolve-Path docs).Path;$mr=(Resolve-Path $m).Path.Substring($dr.Length).TrimStart([char]92).Replace('\','/');if($mr -eq 'meridian-network.md'){$mb=$mb.Replace('(../acupuncture/','(acupuncture/')};U $m '<!-- MERIDIAN_EXPANSION_19_START -->' '<!-- MERIDIAN_EXPANSION_19_END -->' $mb
$a=F @('docs\acupoint-network\index.md','docs\acupoint-network.md','docs\acupuncture\acupoint-network.md') '경혈 임상 지식망';if($a){Copy-Item $a (Join-Path $bk 'acupoint-network.md') -Force;$ab="<!-- ACUPOINT_ATLAS_19_START -->`r`n## 경맥별 주요 경혈 대폭 확장`r`n- **LU** 중부·척택·열결·태연`r`n- **LI** 합곡·수삼리·곡지·견우·영향`r`n- **ST** 천추·족삼리·풍륭·내정`r`n- **SP** 공손·삼음교·음릉천·혈해`r`n- **HT** 소해·통리·신문`r`n- **SI** 후계·양로·천종`r`n- **BL** 천주·폐수·간수·비수·신수·대장수·위중·승산·곤륜`r`n- **KI** 용천·태계·조해·복류`r`n- **PC** 내관·대릉`r`n- **TE** 외관·지구·예풍`r`n- **GB** 풍지·견정·환도·양릉천·현종·구허`r`n- **LR** 태충·곡천·장문·기문`r`n- **CV** 관원·기해·중완·전중`r`n- **GV** 명문·대추·백회·수구`r`n`r`n→ [십이경맥](../acupuncture/meridians/index.md) · [기경팔맥](../acupuncture/extraordinary/index.md)`r`n<!-- ACUPOINT_ATLAS_19_END -->";$ar=(Resolve-Path $a).Path.Substring($dr.Length).TrimStart([char]92).Replace('\','/');if($ar -eq 'acupoint-network.md'){$ab=$ab.Replace('(../acupuncture/','(acupuncture/')};U $a '<!-- ACUPOINT_ATLAS_19_START -->' '<!-- ACUPOINT_ATLAS_19_END -->' $ab}
Write-Host 'MERIDIAN + ACUPOINT EXPANSION 19 COMPLETE' -ForegroundColor Green;Write-Host ('Meridian source: '+$m) -ForegroundColor Cyan;Write-Host ('Acupoint source: '+$a) -ForegroundColor Cyan;Write-Host ('Backup: '+$bk) -ForegroundColor Yellow
}catch{Write-Host ('ERROR: '+$_.Exception.Message) -ForegroundColor Red};Read-Host 'Press Enter to close'
